name: attendance_qr_app
description: A minimal Flutter app for teachers to create QR sessions and take attendance.
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  qr_flutter: ^4.0.0
  uuid: ^3.0.7
  mobile_scanner: ^7.2.0
  supabase_flutter: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
